#!/usr/bin/env python3
"""Seed the paint catalog with Citadel and Vallejo Game Color paints.

Run from project root:
    python scripts/seed_paints.py

Hex values are approximate but representative. Paint types follow the brand's
own range/category names normalised to lowercase.
"""

import os
import sys
from pathlib import Path

# Allow running from project root without installing the package
sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

from app.database import Base
from app.models import Paint

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./mixmini.db")

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {},
)
Session = sessionmaker(bind=engine)

# ---------------------------------------------------------------------------
# Paint data: (brand, range, name, hex, paint_type)
# ---------------------------------------------------------------------------

PAINTS = [
    # -----------------------------------------------------------------------
    # CITADEL — Base
    # -----------------------------------------------------------------------
    ("Citadel", "Base", "Abaddon Black", "#231F20", "base"),
    ("Citadel", "Base", "Averland Sunset", "#F0A800", "base"),
    ("Citadel", "Base", "Balthasar Gold", "#7B5C2A", "base"),
    ("Citadel", "Base", "Bugman's Glow", "#7D3C30", "base"),
    ("Citadel", "Base", "Caledor Sky", "#1B5794", "base"),
    ("Citadel", "Base", "Caliban Green", "#004A2D", "base"),
    ("Citadel", "Base", "Castellan Green", "#3B4A2E", "base"),
    ("Citadel", "Base", "Celestra Grey", "#8D9E97", "base"),
    ("Citadel", "Base", "Chaos Black", "#1A1A1A", "base"),
    ("Citadel", "Base", "Corax White", "#F2F2F2", "base"),
    ("Citadel", "Base", "Corvus Black", "#2A2A2E", "base"),
    ("Citadel", "Base", "Death Guard Green", "#6F7652", "base"),
    ("Citadel", "Base", "Deathworld Forest", "#4A5232", "base"),
    ("Citadel", "Base", "Dryad Bark", "#3E2B1E", "base"),
    ("Citadel", "Base", "Flesh Tearers Red", "#820000", "base"),
    ("Citadel", "Base", "Incubi Darkness", "#1B3A3A", "base"),
    ("Citadel", "Base", "Iron Warriors", "#736C68", "base"),
    ("Citadel", "Base", "Jokaero Orange", "#D0500C", "base"),
    ("Citadel", "Base", "Kantor Blue", "#0E2A5A", "base"),
    ("Citadel", "Base", "Khorne Red", "#6A0E0E", "base"),
    ("Citadel", "Base", "Leadbelcher", "#777A7D", "base"),
    ("Citadel", "Base", "Macragge Blue", "#1C4B8A", "base"),
    ("Citadel", "Base", "Mechanicus Standard Grey", "#606063", "base"),
    ("Citadel", "Base", "Mephiston Red", "#8B1A1A", "base"),
    ("Citadel", "Base", "Mournfang Brown", "#6B3220", "base"),
    ("Citadel", "Base", "Naggaroth Night", "#3A2050", "base"),
    ("Citadel", "Base", "Night Lords Blue", "#1A2E5C", "base"),
    ("Citadel", "Base", "Phoenician Purple", "#4B1A5A", "base"),
    ("Citadel", "Base", "Rakarth Flesh", "#B8A68A", "base"),
    ("Citadel", "Base", "Rhinox Hide", "#4A2018", "base"),
    ("Citadel", "Base", "Screamer Pink", "#A02050", "base"),
    ("Citadel", "Base", "Steel Legion Drab", "#7A6840", "base"),
    ("Citadel", "Base", "Stormvermin Fur", "#7A6E68", "base"),
    ("Citadel", "Base", "The Fang", "#3C5464", "base"),
    ("Citadel", "Base", "Waaagh! Flesh", "#2E5A30", "base"),
    ("Citadel", "Base", "Wraithbone", "#E8DEC0", "base"),
    ("Citadel", "Base", "XV-88", "#6B5028", "base"),
    ("Citadel", "Base", "Zandri Dust", "#9E8A5A", "base"),
    # -----------------------------------------------------------------------
    # CITADEL — Layer
    # -----------------------------------------------------------------------
    ("Citadel", "Layer", "Agrax Earthshade Gloss", "#6B4A2A", "layer"),
    ("Citadel", "Layer", "Alaitoc Blue", "#2E6490", "layer"),
    ("Citadel", "Layer", "Auric Armour Gold", "#B8922A", "layer"),
    ("Citadel", "Layer", "Balor Brown", "#9A6C28", "layer"),
    ("Citadel", "Layer", "Bloodreaver Flesh", "#C04840", "layer"),
    ("Citadel", "Layer", "Brass Scorpion", "#9A5C20", "layer"),
    ("Citadel", "Layer", "Cadian Fleshtone", "#C88060", "layer"),
    ("Citadel", "Layer", "Calgar Blue", "#3A72B8", "layer"),
    ("Citadel", "Layer", "Canoptek Alloy", "#B8A04A", "layer"),
    ("Citadel", "Layer", "Ceramite White", "#FAFAFA", "layer"),
    ("Citadel", "Layer", "Changeling Pink", "#E060A0", "layer"),
    ("Citadel", "Layer", "Counteroffensive Khaki", "#C8B078", "layer"),
    ("Citadel", "Layer", "Darkstrider Green", "#5A7050", "layer"),
    ("Citadel", "Layer", "Dawnstone", "#939390", "layer"),
    ("Citadel", "Layer", "Deathclaw Brown", "#B05C30", "layer"),
    ("Citadel", "Layer", "Dorn Yellow", "#FFD840", "layer"),
    ("Citadel", "Layer", "Dose of Dawnstone", "#939390", "layer"),
    ("Citadel", "Layer", "Elf Flesh", "#E8A880", "layer"),
    ("Citadel", "Layer", "Emperor's Children", "#C03A78", "layer"),
    ("Citadel", "Layer", "Eshin Grey", "#5A5A60", "layer"),
    ("Citadel", "Layer", "Evil Sunz Scarlet", "#B02020", "layer"),
    ("Citadel", "Layer", "Felheart", "#8A5840", "layer"),
    ("Citadel", "Layer", "Fire Dragon Bright", "#E85010", "layer"),
    ("Citadel", "Layer", "Flayed One Flesh", "#D8B88A", "layer"),
    ("Citadel", "Layer", "Flash Gitz Yellow", "#FFF020", "layer"),
    ("Citadel", "Layer", "Gauss Blaster Green", "#70E0A0", "layer"),
    ("Citadel", "Layer", "Genestealer Purple", "#7050A8", "layer"),
    ("Citadel", "Layer", "Gerber Yellow", "#FFE040", "layer"),
    ("Citadel", "Layer", "Hashut Copper", "#A86838", "layer"),
    ("Citadel", "Layer", "Hoeth Blue", "#4090C8", "layer"),
    ("Citadel", "Layer", "Hormagaunt Purple", "#6040A0", "layer"),
    ("Citadel", "Layer", "Howling Banshee White", "#E8E8F0", "layer"),
    ("Citadel", "Layer", "Imrik Blue", "#1A5AB8", "layer"),
    ("Citadel", "Layer", "Ironbreaker", "#9A9EA4", "layer"),
    ("Citadel", "Layer", "Karak Stone", "#C0A870", "layer"),
    ("Citadel", "Layer", "Kabalite Green", "#1E6040", "layer"),
    ("Citadel", "Layer", "Knight-Questor Flesh", "#D8906A", "layer"),
    ("Citadel", "Layer", "Krieg Khaki", "#B8A060", "layer"),
    ("Citadel", "Layer", "Liberator Gold", "#C8982A", "layer"),
    ("Citadel", "Layer", "Loren Forest", "#3E6828", "layer"),
    ("Citadel", "Layer", "Lothern Blue", "#4AB0E8", "layer"),
    ("Citadel", "Layer", "Lucius Lilac", "#B090C8", "layer"),
    ("Citadel", "Layer", "Lugganath Orange", "#E8802A", "layer"),
    ("Citadel", "Layer", "Moot Green", "#38C040", "layer"),
    ("Citadel", "Layer", "Nurgling Green", "#B0C850", "layer"),
    ("Citadel", "Layer", "Ogryn Camo", "#7A8A40", "layer"),
    ("Citadel", "Layer", "Pink Horror", "#D04090", "layer"),
    ("Citadel", "Layer", "Pallid Wych Flesh", "#E0D8C8", "layer"),
    ("Citadel", "Layer", "Russ Grey", "#608898", "layer"),
    ("Citadel", "Layer", "Runefang Steel", "#C0C8D0", "layer"),
    ("Citadel", "Layer", "Screaming Skull", "#D4C890", "layer"),
    ("Citadel", "Layer", "Skarsnik Green", "#58A040", "layer"),
    ("Citadel", "Layer", "Skavenblight Dinge", "#5C5450", "layer"),
    ("Citadel", "Layer", "Slann Blue", "#207098", "layer"),
    ("Citadel", "Layer", "Sotek Green", "#207868", "layer"),
    ("Citadel", "Layer", "Squig Orange", "#C04818", "layer"),
    ("Citadel", "Layer", "Stormhost Silver", "#D8DDE0", "layer"),
    ("Citadel", "Layer", "Sycorax Bronze", "#A87840", "layer"),
    ("Citadel", "Layer", "Tau Light Ochre", "#C08830", "layer"),
    ("Citadel", "Layer", "Temple Guard Blue", "#30A0A8", "layer"),
    ("Citadel", "Layer", "Thunderhawk Blue", "#386080", "layer"),
    ("Citadel", "Layer", "Troll Slayer Orange", "#E85A00", "layer"),
    ("Citadel", "Layer", "Ulthuan Grey", "#D8E0DC", "layer"),
    ("Citadel", "Layer", "Ushabti Bone", "#C0A870", "layer"),
    ("Citadel", "Layer", "Vallhallan Blizzard", "#D8E8F0", "layer"),
    ("Citadel", "Layer", "Vulkan Green", "#184A30", "layer"),
    ("Citadel", "Layer", "Warboss Green", "#307A38", "layer"),
    ("Citadel", "Layer", "White Scar", "#FEFEFE", "layer"),
    ("Citadel", "Layer", "Wild Rider Red", "#C82818", "layer"),
    ("Citadel", "Layer", "Wych Flesh", "#D09878", "layer"),
    ("Citadel", "Layer", "Yriel Yellow", "#F8D800", "layer"),
    ("Citadel", "Layer", "Zamesi Desert", "#C8A040", "layer"),
    # -----------------------------------------------------------------------
    # CITADEL — Shade
    # -----------------------------------------------------------------------
    ("Citadel", "Shade", "Agrax Earthshade", "#5A3818", "shade"),
    ("Citadel", "Shade", "Athonian Camoshade", "#3A5028", "shade"),
    ("Citadel", "Shade", "Biel-Tan Green", "#1A5028", "shade"),
    ("Citadel", "Shade", "Carroburg Crimson", "#700020", "shade"),
    ("Citadel", "Shade", "Casandora Yellow", "#D08000", "shade"),
    ("Citadel", "Shade", "Coelia Greenshade", "#185040", "shade"),
    ("Citadel", "Shade", "Cryptek Armourshade Gloss", "#3A3A3A", "shade"),
    ("Citadel", "Shade", "Drakenhof Nightshade", "#101840", "shade"),
    ("Citadel", "Shade", "Druchii Violet", "#3A1050", "shade"),
    ("Citadel", "Shade", "Fuegan Orange", "#A03800", "shade"),
    ("Citadel", "Shade", "Hexos Palesun", "#C0B020", "shade"),
    ("Citadel", "Shade", "Kroak Green", "#208050", "shade"),
    ("Citadel", "Shade", "Leviadon Blue", "#082840", "shade"),
    ("Citadel", "Shade", "Lugganath Orange Shade", "#A04000", "shade"),
    ("Citadel", "Shade", "Mortarion Grime", "#506040", "shade"),
    ("Citadel", "Shade", "Nagarroth Night", "#280840", "shade"),
    ("Citadel", "Shade", "Nuln Oil", "#1A1A1A", "shade"),
    ("Citadel", "Shade", "Nuln Oil Gloss", "#1A1A1A", "shade"),
    ("Citadel", "Shade", "Poxwalker", "#404020", "shade"),
    ("Citadel", "Shade", "Reikland Fleshshade", "#803018", "shade"),
    ("Citadel", "Shade", "Reikland Fleshshade Gloss", "#803018", "shade"),
    ("Citadel", "Shade", "Seraphim Sepia", "#806018", "shade"),
    ("Citadel", "Shade", "Soulblight Grey", "#404048", "shade"),
    ("Citadel", "Shade", "Targor Rageshade", "#7A2828", "shade"),
    ("Citadel", "Shade", "Tyran Blue", "#103070", "shade"),
    # -----------------------------------------------------------------------
    # CITADEL — Dry
    # -----------------------------------------------------------------------
    ("Citadel", "Dry", "Administratum Grey", "#B8B8B8", "dry"),
    ("Citadel", "Dry", "Ahriman Blue", "#407898", "dry"),
    ("Citadel", "Dry", "Astorath Red", "#D02020", "dry"),
    ("Citadel", "Dry", "Astrogranite Debris", "#686870", "dry"),
    ("Citadel", "Dry", "Baneblade Brown", "#9A7A58", "dry"),
    ("Citadel", "Dry", "Bauhaus Sienna", "#9A6030", "dry"),
    ("Citadel", "Dry", "Brightstone", "#E0D890", "dry"),
    ("Citadel", "Dry", "Changeling Pink Dry", "#E858A8", "dry"),
    ("Citadel", "Dry", "Chronus Blue", "#2870C0", "dry"),
    ("Citadel", "Dry", "Eldar Flesh", "#D0906A", "dry"),
    ("Citadel", "Dry", "Etherium Blue", "#90C8D0", "dry"),
    ("Citadel", "Dry", "Faeit Grey", "#909098", "dry"),
    ("Citadel", "Dry", "Golgfag Brown", "#8A5828", "dry"),
    ("Citadel", "Dry", "Hexos Palesun Dry", "#F0E060", "dry"),
    ("Citadel", "Dry", "Imrik Blue Dry", "#3880D0", "dry"),
    ("Citadel", "Dry", "Longbeard Grey", "#C0C0B8", "dry"),
    ("Citadel", "Dry", "Lucius Lilac Dry", "#C0A0D8", "dry"),
    ("Citadel", "Dry", "Necron Compound", "#C8D0C8", "dry"),
    ("Citadel", "Dry", "Nurgling Green Dry", "#C0D060", "dry"),
    ("Citadel", "Dry", "Praxeti White", "#E8E8E8", "dry"),
    ("Citadel", "Dry", "Rockgut Troglodyte", "#688078", "dry"),
    ("Citadel", "Dry", "Ryza Rust", "#B05818", "dry"),
    ("Citadel", "Dry", "Slaanesh Grey", "#B0B0C0", "dry"),
    ("Citadel", "Dry", "Terminatus Stone", "#C8B890", "dry"),
    ("Citadel", "Dry", "Tyrant Shell", "#E8D0A0", "dry"),
    ("Citadel", "Dry", "Underhive Ash", "#D0C8A0", "dry"),
    ("Citadel", "Dry", "Wurmspat Green", "#607850", "dry"),
    # -----------------------------------------------------------------------
    # CITADEL — Contrast
    # -----------------------------------------------------------------------
    ("Citadel", "Contrast", "Aggaros Dunes", "#C8901C", "contrast"),
    ("Citadel", "Contrast", "Akhelian Green", "#008060", "contrast"),
    ("Citadel", "Contrast", "Apothecary White", "#D8DCD8", "contrast"),
    ("Citadel", "Contrast", "Aethermatic Blue", "#4898C8", "contrast"),
    ("Citadel", "Contrast", "Bad Moon Yellow", "#E8C000", "contrast"),
    ("Citadel", "Contrast", "Basilicanum Grey", "#484850", "contrast"),
    ("Citadel", "Contrast", "Black Templar", "#1C1C20", "contrast"),
    ("Citadel", "Contrast", "Blood Angels Red", "#901010", "contrast"),
    ("Citadel", "Contrast", "Blistered Shin", "#B84818", "contrast"),
    ("Citadel", "Contrast", "Celestium Blue", "#204898", "contrast"),
    ("Citadel", "Contrast", "Creed Camo", "#407038", "contrast"),
    ("Citadel", "Contrast", "Dark Angels Green", "#0A4820", "contrast"),
    ("Citadel", "Contrast", "Darkoath Flesh", "#C07050", "contrast"),
    ("Citadel", "Contrast", "Death Guard Green", "#506838", "contrast"),
    ("Citadel", "Contrast", "Doomfire Magenta", "#A0005A", "contrast"),
    ("Citadel", "Contrast", "Drakenof Nightshade", "#0A1840", "contrast"),
    ("Citadel", "Contrast", "Flesh Tearers Red", "#780808", "contrast"),
    ("Citadel", "Contrast", "Fyreslayer Flesh", "#D06048", "contrast"),
    ("Citadel", "Contrast", "Garaghak's Sewer", "#505038", "contrast"),
    ("Citadel", "Contrast", "Gutrippa Flesh", "#B06A50", "contrast"),
    ("Citadel", "Contrast", "Guilliman Flesh", "#C07858", "contrast"),
    ("Citadel", "Contrast", "Gryph-charger Grey", "#507090", "contrast"),
    ("Citadel", "Contrast", "Gryph-hound Orange", "#C04000", "contrast"),
    ("Citadel", "Contrast", "Ironjawz Yellow", "#D89000", "contrast"),
    ("Citadel", "Contrast", "Leviathan Purple", "#501870", "contrast"),
    ("Citadel", "Contrast", "Luxion Purple", "#400870", "contrast"),
    ("Citadel", "Contrast", "Magmadroth Flame", "#D03000", "contrast"),
    ("Citadel", "Contrast", "Militarum Green", "#384820", "contrast"),
    ("Citadel", "Contrast", "Morghast Bone", "#C8B870", "contrast"),
    ("Citadel", "Contrast", "Nazdreg Yellow", "#E0A800", "contrast"),
    ("Citadel", "Contrast", "Nighthaunt Gloom", "#388890", "contrast"),
    ("Citadel", "Contrast", "Ork Flesh", "#286030", "contrast"),
    ("Citadel", "Contrast", "Pylar Glacier", "#80C0D8", "contrast"),
    ("Citadel", "Contrast", "Ratskaven Pink", "#C04080", "contrast"),
    ("Citadel", "Contrast", "Shyish Purple", "#380060", "contrast"),
    ("Citadel", "Contrast", "Sigmarite", "#B07828", "contrast"),
    ("Citadel", "Contrast", "Skeleton Horde", "#C8B060", "contrast"),
    ("Citadel", "Contrast", "Snakebite Leather", "#8A5A20", "contrast"),
    ("Citadel", "Contrast", "Space Wolves Grey", "#5880A0", "contrast"),
    ("Citadel", "Contrast", "Striking Scorpion Green", "#006830", "contrast"),
    ("Citadel", "Contrast", "Talassar Blue", "#103878", "contrast"),
    ("Citadel", "Contrast", "Terradon Turquoise", "#007878", "contrast"),
    ("Citadel", "Contrast", "Volupus Pink", "#980060", "contrast"),
    ("Citadel", "Contrast", "Warp Lightning", "#288A20", "contrast"),
    ("Citadel", "Contrast", "Wyldwood", "#382818", "contrast"),
    # -----------------------------------------------------------------------
    # CITADEL — Technical
    # -----------------------------------------------------------------------
    ("Citadel", "Technical", "Agrellan Badlands", "#A07840", "technical"),
    ("Citadel", "Technical", "Agrellan Earth", "#907040", "technical"),
    ("Citadel", "Technical", "Armageddon Dunes", "#C09060", "technical"),
    ("Citadel", "Technical", "Armageddon Dust", "#B89060", "technical"),
    ("Citadel", "Technical", "Blood for the Blood God", "#880000", "technical"),
    ("Citadel", "Technical", "Contrast Medium", "#E8E8E8", "technical"),
    ("Citadel", "Technical", "Gemstone Blue", "#0050C0", "technical"),
    ("Citadel", "Technical", "Gemstone Emerald", "#004A30", "technical"),
    ("Citadel", "Technical", "Gemstone Red", "#800000", "technical"),
    ("Citadel", "Technical", "Gemstone Purple", "#400060", "technical"),
    ("Citadel", "Technical", "Lahmian Medium", "#F8F8F8", "technical"),
    ("Citadel", "Technical", "Lustrous Gold", "#C89820", "technical"),
    ("Citadel", "Technical", "Mirrorman's Aethersheen", "#D0D8E0", "technical"),
    ("Citadel", "Technical", "Mordant Earth", "#483020", "technical"),
    ("Citadel", "Technical", "Nihilakh Oxide", "#70B0A0", "technical"),
    ("Citadel", "Technical", "Nurgles Rot", "#406830", "technical"),
    ("Citadel", "Technical", "Oxide Blue", "#608090", "technical"),
    ("Citadel", "Technical", "Purity Seal", "#F0F0F0", "technical"),
    ("Citadel", "Technical", "Spiritstone Red", "#A00000", "technical"),
    ("Citadel", "Technical", "Stormshield", "#E8E8E0", "technical"),
    ("Citadel", "Technical", "Typhus Corrosion", "#303820", "technical"),
    ("Citadel", "Technical", "Valhallan Blizzard", "#E0F0F8", "technical"),
    ("Citadel", "Technical", "Waystone Green", "#104A20", "technical"),
    # -----------------------------------------------------------------------
    # VALLEJO — Game Color (core range)
    # -----------------------------------------------------------------------
    ("Vallejo", "Game Color", "Dead White", "#FAFAFA", "base"),
    ("Vallejo", "Game Color", "Ivory", "#FFFFF0", "base"),
    ("Vallejo", "Game Color", "Pale Flesh", "#F0C8A0", "base"),
    ("Vallejo", "Game Color", "Dwarf Skin", "#C88060", "base"),
    ("Vallejo", "Game Color", "Heavy Skintone", "#C07050", "base"),
    ("Vallejo", "Game Color", "Elf Skintone", "#E8A880", "base"),
    ("Vallejo", "Game Color", "Dark Flesh", "#904038", "base"),
    ("Vallejo", "Game Color", "Tan", "#C09060", "base"),
    ("Vallejo", "Game Color", "Leather Brown", "#7A4820", "base"),
    ("Vallejo", "Game Color", "Beasty Brown", "#6A4018", "base"),
    ("Vallejo", "Game Color", "Bronze Flesh", "#C07848", "base"),
    ("Vallejo", "Game Color", "Plague Brown", "#98884A", "base"),
    ("Vallejo", "Game Color", "Filthy Brown", "#808050", "base"),
    ("Vallejo", "Game Color", "Desert Yellow", "#C0A858", "base"),
    ("Vallejo", "Game Color", "Dead Flesh", "#D8C8A0", "base"),
    ("Vallejo", "Game Color", "Khaki", "#C0B078", "base"),
    ("Vallejo", "Game Color", "Bone White", "#E0D0A8", "base"),
    ("Vallejo", "Game Color", "Gold Yellow", "#F0C020", "base"),
    ("Vallejo", "Game Color", "Sun Yellow", "#F8D800", "base"),
    ("Vallejo", "Game Color", "Hot Orange", "#E85010", "base"),
    ("Vallejo", "Game Color", "Fireball Orange", "#E87800", "base"),
    ("Vallejo", "Game Color", "Scarlett Red", "#C00000", "base"),
    ("Vallejo", "Game Color", "Gory Red", "#980000", "base"),
    ("Vallejo", "Game Color", "Blood Red", "#B80000", "base"),
    ("Vallejo", "Game Color", "Terracotta", "#A04028", "base"),
    ("Vallejo", "Game Color", "Red Gore", "#800000", "base"),
    ("Vallejo", "Game Color", "Nocturnal Red", "#580000", "base"),
    ("Vallejo", "Game Color", "Warlord Purple", "#801870", "base"),
    ("Vallejo", "Game Color", "Hexed Lichen", "#502870", "base"),
    ("Vallejo", "Game Color", "Alien Purple", "#684898", "base"),
    ("Vallejo", "Game Color", "Magic Blue", "#3060B0", "base"),
    ("Vallejo", "Game Color", "Electric Blue", "#3898E0", "base"),
    ("Vallejo", "Game Color", "Ultramarine Blue", "#1840A0", "base"),
    ("Vallejo", "Game Color", "Imperial Blue", "#082070", "base"),
    ("Vallejo", "Game Color", "Dark Blue", "#082048", "base"),
    ("Vallejo", "Game Color", "Heavy Blue", "#204880", "base"),
    ("Vallejo", "Game Color", "Glacier Blue", "#80B8C8", "base"),
    ("Vallejo", "Game Color", "Ice Blue", "#A8D0E0", "base"),
    ("Vallejo", "Game Color", "Stonewall Grey", "#B0B0B0", "base"),
    ("Vallejo", "Game Color", "Wolf Grey", "#9098A8", "base"),
    ("Vallejo", "Game Color", "Space Grey", "#505060", "base"),
    ("Vallejo", "Game Color", "Foul Green", "#508840", "base"),
    ("Vallejo", "Game Color", "Goblin Green", "#289030", "base"),
    ("Vallejo", "Game Color", "Sick Green", "#688848", "base"),
    ("Vallejo", "Game Color", "Cayman Green", "#307858", "base"),
    ("Vallejo", "Game Color", "Jade Green", "#208858", "base"),
    ("Vallejo", "Game Color", "Livery Green", "#105830", "base"),
    ("Vallejo", "Game Color", "Dark Green", "#083820", "base"),
    ("Vallejo", "Game Color", "Olive Green", "#688038", "base"),
    ("Vallejo", "Game Color", "Camouflage Green", "#607840", "base"),
    ("Vallejo", "Game Color", "Forest Green", "#305028", "base"),
    ("Vallejo", "Game Color", "Hawk Turquoise", "#008880", "base"),
    ("Vallejo", "Game Color", "Scurvy Green", "#608870", "base"),
    ("Vallejo", "Game Color", "Seagreen", "#208070", "base"),
    ("Vallejo", "Game Color", "Turquoise", "#10A8A8", "base"),
    ("Vallejo", "Game Color", "Coal Black", "#282828", "base"),
    ("Vallejo", "Game Color", "Black", "#181818", "base"),
    ("Vallejo", "Game Color", "Charcoal", "#3A3A3A", "base"),
    ("Vallejo", "Game Color", "Heavy Charcoal", "#2A2A2A", "base"),
    ("Vallejo", "Game Color", "Sombre Grey", "#606068", "base"),
    ("Vallejo", "Game Color", "Gunmetal", "#707880", "base"),
    ("Vallejo", "Game Color", "Cold Grey", "#888898", "base"),
    ("Vallejo", "Game Color", "Pale Grey Blue", "#B0B8C8", "base"),
    ("Vallejo", "Game Color", "White", "#FEFEFE", "base"),
    ("Vallejo", "Game Color", "Ghost Grey", "#D8D8D8", "base"),
    ("Vallejo", "Game Color", "Offwhite", "#F0EEE0", "base"),
    ("Vallejo", "Game Color", "Chainmail Silver", "#B0B8C0", "base"),
    ("Vallejo", "Game Color", "Glorious Gold", "#C89820", "base"),
    ("Vallejo", "Game Color", "Bright Bronze", "#A87830", "base"),
    ("Vallejo", "Game Color", "Polished Gold", "#D8A820", "base"),
    ("Vallejo", "Game Color", "Shining Silver", "#D0D8E0", "base"),
    ("Vallejo", "Game Color", "Hammered Copper", "#985028", "base"),
    ("Vallejo", "Game Color", "Brassy Brass", "#A07020", "base"),
    ("Vallejo", "Game Color", "Tinny Tin", "#806030", "base"),
    ("Vallejo", "Game Color", "Dirty White", "#E8E0D0", "base"),
    ("Vallejo", "Game Color", "Dwarven Skin", "#C07050", "base"),
    ("Vallejo", "Game Color", "Sand Yellow", "#C8B070", "base"),
    ("Vallejo", "Game Color", "Barbarian Leather", "#8A5020", "base"),
    ("Vallejo", "Game Color", "Earth", "#7A5830", "base"),
    ("Vallejo", "Game Color", "Vermin Brown", "#6A3818", "base"),
    ("Vallejo", "Game Color", "Scrofulous Brown", "#A07840", "base"),
    ("Vallejo", "Game Color", "Parasite Brown", "#582810", "base"),
    ("Vallejo", "Game Color", "Heavy Brown", "#5A3820", "base"),
    ("Vallejo", "Game Color", "Cobra Leather", "#7A5038", "base"),
    ("Vallejo", "Game Color", "Bestial Brown", "#6A3820", "base"),
    ("Vallejo", "Game Color", "Charred Brown", "#402010", "base"),
    ("Vallejo", "Game Color", "Heavy Red", "#900000", "base"),
    ("Vallejo", "Game Color", "Lava Orange", "#D86010", "base"),
    ("Vallejo", "Game Color", "Squid Pink", "#D85090", "base"),
    ("Vallejo", "Game Color", "Pale Flesh Vallejo", "#F0C898", "base"),
    ("Vallejo", "Game Color", "Heavy Sienna", "#783818", "base"),
    ("Vallejo", "Game Color", "Flesh Rose", "#E89878", "base"),
    ("Vallejo", "Game Color", "Rosy Flesh", "#D88870", "base"),
    ("Vallejo", "Game Color", "Tentacle Pink", "#E060A0", "base"),
    ("Vallejo", "Game Color", "Pink", "#E888B0", "base"),
    ("Vallejo", "Game Color", "Warlock Purple", "#581870", "base"),
    ("Vallejo", "Game Color", "Royal Purple", "#401060", "base"),
    ("Vallejo", "Game Color", "Purple", "#5A1878", "base"),
    ("Vallejo", "Game Color", "Scaly Green", "#387850", "base"),
    ("Vallejo", "Game Color", "Mold Green", "#508050", "base"),
    ("Vallejo", "Game Color", "Goblin Green VGC", "#308038", "base"),
    # -----------------------------------------------------------------------
    # VALLEJO — Game Color Wash
    # -----------------------------------------------------------------------
    ("Vallejo", "Game Color Wash", "Dark Brown Wash", "#3A2010", "shade"),
    ("Vallejo", "Game Color Wash", "Brown Wash", "#5A3818", "shade"),
    ("Vallejo", "Game Color Wash", "Dark Tone Wash", "#181818", "shade"),
    ("Vallejo", "Game Color Wash", "Soft Tone Wash", "#806040", "shade"),
    ("Vallejo", "Game Color Wash", "Strong Tone Wash", "#503010", "shade"),
    ("Vallejo", "Game Color Wash", "Blue Tone Wash", "#083060", "shade"),
    ("Vallejo", "Game Color Wash", "Green Tone Wash", "#083820", "shade"),
    ("Vallejo", "Game Color Wash", "Purple Tone Wash", "#280848", "shade"),
    ("Vallejo", "Game Color Wash", "Red Wash", "#700000", "shade"),
    ("Vallejo", "Game Color Wash", "Skin Wash", "#703020", "shade"),
    ("Vallejo", "Game Color Wash", "Yellow Shade Wash", "#806000", "shade"),
    ("Vallejo", "Game Color Wash", "Sepia Shade", "#604818", "shade"),
    ("Vallejo", "Game Color Wash", "Umber Shade", "#402808", "shade"),
    # -----------------------------------------------------------------------
    # VALLEJO — Game Color Extra Opaque
    # -----------------------------------------------------------------------
    ("Vallejo", "Game Color Extra Opaque", "Heavy Red", "#A00000", "base"),
    ("Vallejo", "Game Color Extra Opaque", "Heavy Orange", "#D05A00", "base"),
    ("Vallejo", "Game Color Extra Opaque", "Heavy Yellow", "#F0C800", "base"),
    ("Vallejo", "Game Color Extra Opaque", "Heavy Green", "#187830", "base"),
    ("Vallejo", "Game Color Extra Opaque", "Heavy Dark Green", "#0A4818", "base"),
    ("Vallejo", "Game Color Extra Opaque", "Heavy Blue", "#1040A0", "base"),
    ("Vallejo", "Game Color Extra Opaque", "Heavy Violet", "#4010A0", "base"),
    ("Vallejo", "Game Color Extra Opaque", "Heavy Warm Grey", "#909080", "base"),
    ("Vallejo", "Game Color Extra Opaque", "Heavy Black Grey", "#282830", "base"),
    ("Vallejo", "Game Color Extra Opaque", "Heavy Grey", "#808080", "base"),
    # -----------------------------------------------------------------------
    # VALLEJO — Game Color Fluorescent
    # -----------------------------------------------------------------------
    ("Vallejo", "Game Color Fluorescent", "Fluo Orange", "#FF8000", "base"),
    ("Vallejo", "Game Color Fluorescent", "Fluo Yellow", "#F8FF00", "base"),
    ("Vallejo", "Game Color Fluorescent", "Fluo Green", "#00FF60", "base"),
    ("Vallejo", "Game Color Fluorescent", "Fluo Blue", "#0080FF", "base"),
    ("Vallejo", "Game Color Fluorescent", "Fluo Pink", "#FF40A0", "base"),
    ("Vallejo", "Game Color Fluorescent", "Fluo Red", "#FF2000", "base"),
    # -----------------------------------------------------------------------
    # VALLEJO — Game Air (airbrush range, also useful for regular painting)
    # -----------------------------------------------------------------------
    ("Vallejo", "Game Air", "Black", "#181818", "air"),
    ("Vallejo", "Game Air", "White", "#FEFEFE", "air"),
    ("Vallejo", "Game Air", "Ultramarine Blue", "#1840A0", "air"),
    ("Vallejo", "Game Air", "Electric Blue", "#3898E0", "air"),
    ("Vallejo", "Game Air", "Goblin Green", "#289030", "air"),
    ("Vallejo", "Game Air", "Hot Orange", "#E85010", "air"),
    ("Vallejo", "Game Air", "Scarlett Red", "#C00000", "air"),
    ("Vallejo", "Game Air", "Sun Yellow", "#F8D800", "air"),
    ("Vallejo", "Game Air", "Gold", "#C89820", "air"),
    ("Vallejo", "Game Air", "Silver", "#C0C8D0", "air"),
    ("Vallejo", "Game Air", "Bronze", "#A07020", "air"),
    ("Vallejo", "Game Air", "Gunmetal", "#707880", "air"),
    ("Vallejo", "Game Air", "Hexed Lichen", "#502870", "air"),
    ("Vallejo", "Game Air", "Camouflage Green", "#607840", "air"),
    ("Vallejo", "Game Air", "Desert Yellow", "#C0A858", "air"),
    ("Vallejo", "Game Air", "Khaki", "#C0B078", "air"),
    ("Vallejo", "Game Air", "Dark Flesh", "#904038", "air"),
    ("Vallejo", "Game Air", "Tan", "#C09060", "air"),
    ("Vallejo", "Game Air", "Wolf Grey", "#9098A8", "air"),
    ("Vallejo", "Game Air", "Cold Grey", "#888898", "air"),
    ("Vallejo", "Game Air", "Turquoise", "#10A8A8", "air"),
    ("Vallejo", "Game Air", "Jade Green", "#208858", "air"),
    ("Vallejo", "Game Air", "Warlock Purple", "#581870", "air"),
    ("Vallejo", "Game Air", "Imperial Blue", "#082070", "air"),
    ("Vallejo", "Game Air", "Terracotta", "#A04028", "air"),
    ("Vallejo", "Game Air", "Red Gore", "#800000", "air"),
    ("Vallejo", "Game Air", "Stonewall Grey", "#B0B0B0", "air"),
    ("Vallejo", "Game Air", "Leather Brown", "#7A4820", "air"),
    ("Vallejo", "Game Air", "Blood Red", "#B80000", "air"),
    ("Vallejo", "Game Air", "Squid Pink", "#D85090", "air"),
    ("Vallejo", "Game Air", "Tentacle Pink", "#E060A0", "air"),
    ("Vallejo", "Game Air", "Foul Green", "#508840", "air"),
    ("Vallejo", "Game Air", "Ice Blue", "#A8D0E0", "air"),
    ("Vallejo", "Game Air", "Warlord Purple", "#801870", "air"),
    ("Vallejo", "Game Air", "Pale Flesh", "#F0C8A0", "air"),
]


def seed():
    session = Session()
    try:
        existing = session.query(Paint).count()
        if existing > 0:
            print(f"Paint catalog already seeded ({existing} paints). Skipping.")
            return

        paints = [
            Paint(brand=brand, range=rng, name=name, hex=hex_val, paint_type=ptype)
            for brand, rng, name, hex_val, ptype in PAINTS
        ]
        session.bulk_save_objects(paints)
        session.commit()
        print(f"Seeded {len(paints)} paints into catalog.")
    finally:
        session.close()


if __name__ == "__main__":
    seed()
